### ISSUE TITLE
(FLK-E711) Equality comparison detected with singleton object

### ISSUE THREAD

**Issue by Dank-del** [AnimeKaizoku/EnterpriseALRobot#118]
## Description
Comparisons to the singleton objects, like `True`, `False`, and `None`, should be done with identity, not equality. Use “is” or “is not”. Identity checks are faster than equality checks. Bad: ```python value = fx() if value != None: print(value) ``` Good: ```python value = fx() if value is not None: …

## Occurrences
There are 29 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/Dank-del/EnterpriseALRobot/issue/FLK-E711/occurrences/](https://deepsource.io/gh/Dank-del/EnterpriseALRobot/issue/FLK-E711/occurrences/)

**Comment by Wackyator** [comment]
@Dank-del pro

**Comment by Dank-del** [comment]
> @Dank-del pro

you. Now shush.
