### ISSUE TITLE
Request to add a feature plug-in

### ISSUE THREAD

**Issue by ShadowsSide** [AnimeKaizoku/EnterpriseALRobot#252]
https://github.com/TheHamkerCat/LunaChatBot

I think it will make the bot more interesting. LOL

**Comment by ShadowsSide** [comment]
This is a Telegram AI Chat bot plug-in

**Comment by Dank-del** [comment]
no we dont, want chatbot in group manager bot

hence we have seperate bots: https://t.me/KaizokuBots/1390

**Comment by ShadowsSide** [comment]
Thanks!
